version: "3.8"

services:
  api:
    build: .
    container_name: "django-rest-api"
    command: ./entrypoint.sh
    hostname: api
    volumes:
      - django_static_volume:/usr/src/app/static
    ports:
      - 8000
    env_file:
      - .env
    links:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=todos_user
      - POSTGRES_PASSWORD=todos_password!
      - POSTGRES_DB=db_todos

volumes:
  postgres_data:
  django_static_volume:
